## Imports

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Get data into a pandas dataframe

In [114]:
biographical = pd.read_excel("01 scorecard_dataset.xlsx", sheet_name=0)
biographical.head()

      ID  Gender Education  Offences
0  10005    Male  Grade 12         4
1  10026    Male  Grade 12         0
2  10031    Male    Degree         0
3  10034  Female  Grade 12         0
4  10057    Male  Grade 12         2

In [122]:
filename = "01 scorecard_dataset.xlsx"
with pd.ExcelFile(filename) as xls:
    sheet_names = xls.sheet_names[1:]
    print(sheet_names)
    sheetlist = [pd.read_excel(xls, sheet_name=name) for name in sheet_names]

#sheetlist[1].head()
credit_df = pd.concat(sheetlist, ignore_index=True)
credit_df.head()

['ID1', 'ID2', 'ID3', 'ID4', 'ID5', 'ID6', 'ID7', 'ID8', 'ID9']

      ID  Gender Education  Offences
0  10005    Male  Grade 12         4
1  10026    Male  Grade 12         0
2  10031    Male    Degree         0
3  10034  Female  Grade 12         0
4  10057    Male  Grade 12         2

## Save as .csv files

In [102]:
biographical.to_csv("Biographical_raw.csv", index=False)
credit_df.to_csv("Credit_data_raw.csv", index=False)

In [50]:
biographical = pd.read_csv("Biographical_raw.csv")
credit_df = pd.read_csv("Credit_data_raw.csv")

# Clean the data of Biographical

**Inspect the data**

In [51]:
biographical.dtypes

ID            int64
Gender       object
Education    object
Offences      int64
dtype: object

In [52]:
biographical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
ID           10000 non-null int64
Gender       10000 non-null object
Education    10000 non-null object
Offences     10000 non-null int64
dtypes: int64(2), object(2)
memory usage: 312.6+ KB

In [53]:
biographical.describe()

                 ID      Offences
count  10000.000000  10000.000000
mean   55268.985100      0.668800
std    25973.174166      0.940423
min    10005.000000      0.000000
25%    32593.000000      0.000000
50%    55344.500000      0.000000
75%    77491.250000      1.000000
max    99997.000000      4.000000

In [65]:
num_males_bio = len(biographical[biographical["Gender"] == "Male"])

5017

In [66]:
num_females_bio = len(biographical[biographical["Gender"] == "Female"])

4983

## Identify messy data

** 1. ID should be a string **

In [54]:
biographical["ID"] = biographical["ID"].astype(str)
biographical.dtypes

ID           object
Gender       object
Education    object
Offences      int64
dtype: object

In [55]:
biographical.head()

      ID  Gender Education  Offences
0  10005    Male  Grade 12         4
1  10026    Male  Grade 12         0
2  10031    Male    Degree         0
3  10034  Female  Grade 12         0
4  10057    Male  Grade 12         2

In [78]:
biographical["Education"].value_counts()

Grade 12      3515
Diploma       2553
No records    1947
Degree        1479
Postgrad       506
Name: Education, dtype: int64

** 2. Check if all offences is of numeric type**

In [61]:
biographical['Offences'] = pd.to_numeric(biographical['Offences'], errors='coerce')
null_offence = pd.isnull(biographical['Offences']).sum()

if null_offence == 0:
    print("There are 0 Na occurances which means all values are numeric")
else:
    print("There are Na values. Inspect further.")

There are 0 Na occurances which means all values are numeric

** 3. Check for missing values **

In [67]:
biographical.isnull().sum()

ID           0
Gender       0
Education    0
Offences     0
dtype: int64

** 4.1. Check for spelling mistakes in Gender **

In [72]:
valid_Genders = ["Male", "Female"]
invalid_Gender_idx = biographical[~biographical["Gender"].isin(valid_Genders)] 
if (len(invalid_Gender_idx) == 0):
    print("No spelling errors in Gender")

No spelling errors in Gender

** 4.2. Check for spelling mistakes in Education **

In [80]:
valid_Education = ["Grade 12", "Degree", "Diploma", "Postgrad", "No records"]
invalid_Education_idx = biographical[~biographical["Education"].isin(valid_Education)] 
if (len(invalid_Education_idx) == 0):
    print("No spelling errors in Education")
else:
    print("Inspect: "+ str(len(invalid_Education_idx)) + " errors" )

No spelling errors in Education

In [82]:
biographical.head()

      ID  Gender Education  Offences
0  10005    Male  Grade 12         4
1  10026    Male  Grade 12         0
2  10031    Male    Degree         0
3  10034  Female  Grade 12         0
4  10057    Male  Grade 12         2

In [85]:
biographical.dtypes

ID           object
Gender       object
Education    object
Offences      int64
dtype: object

** Save cleaned biographical dataset **

In [90]:
biographical.to_csv("biographical_clean.csv")
biographical_KnownEd = biographical[~(biographical["Education"]=="No records")]
biographical_KnownEd.to_csv("biographical_clean_KnownEd")